import { NextResponse } from 'next/server';
import { getCourses, saveCourse } from '@/lib/server/courseStore';
import { Course, Module } from '@/lib/types';
import { INITIAL_COURSES } from '@/lib/initial-data';

export async function GET() {
  try {
    // Fetch real courses generated by AI/User
    const dbCourses = await getCourses();

    // Combine Dummy Data + Real Data
    // We check if IDs exist to avoid duplicates if you save dummy data to DB later
    const allCourses = [...INITIAL_COURSES, ...dbCourses];

    return NextResponse.json(allCourses);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch courses' }, { status: 500 });
  }
}