export type Lesson = {
  id: string;
  title: string;
  duration: string;
  videoUrl: string; // Default YouTube link
  completed: boolean;
  notes?: string;
  type: 'video' | 'quiz' | 'reading';
};

export type Module = {
  id: string;
  title: string;
  lessons: Lesson[];
  quiz?: Quiz; // End of section quiz
};

export type Quiz = {
  id: string;
  questions: {
    question: string;
    options: string[];
    correctAnswer: number;
  }[];
  score?: number;
  completed: boolean;
};

export type Course = {
  id: string;
  title: string;
  description: string;
  category: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  imageUrl: string; // Generated by Gemini
  progress: number;
  totalLessons: number;
  completedLessons: number;
  modules: Module[];
  startDate?: string;
  endDate?: string;
  studentName?: string;
  isAssigned?: boolean;
};