'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { Sidebar } from '@/components/sidebar';
import { Topbar } from '@/components/topbar';
import { CheckCircle, XCircle, AlertCircle, ArrowLeft } from 'lucide-react';

export default function QuizPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const router = useRouter();
  
  // Get details from URL query (passed from Course Page)
  const moduleId = searchParams.get('moduleId');
  const topic = searchParams.get('topic');

  const [questions, setQuestions] = useState<any[]>([]);
  const [userAnswers, setUserAnswers] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [submitted, setSubmitted] = useState(false);
  const [result, setResult] = useState<any>(null);

  // 1. Generate Quiz on Load
  useEffect(() => {
    const generate = async () => {
      try {
        const res = await fetch('/api/tests/generate', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ 
            topic: topic || 'General Course Knowledge', 
            difficulty: 'Intermediate',
            questionCount: 5 
          })
        });
        const data = await res.json();
        setQuestions(data.questions);
      } catch (e) {
        alert("Failed to generate test.");
      } finally {
        setLoading(false);
      }
    };
    generate();
  }, [topic]);

  // 2. Handle Answer Selection
  const handleSelect = (qId: string, option: string) => {
    if (submitted) return;
    setUserAnswers(prev => ({ ...prev, [qId]: option }));
  };

  // 3. Submit and Store
  const handleSubmit = async () => {
    setLoading(true);
    const res = await fetch('/api/tests/submit', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        courseId: params.id,
        moduleId: moduleId,
        userAnswers,
        originalQuestions: questions
      })
    });
    const data = await res.json();
    setResult(data.result);
    setSubmitted(true);
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-[#f7f7f5]">
      <Sidebar />
      <div className="ml-20">
        <Topbar userName="Learner" />
        <main className="p-8 max-w-3xl mx-auto">
          
          <button onClick={() => router.back()} className="mb-6 flex items-center gap-2 text-gray-500 font-bold hover:text-black">
             <ArrowLeft size={20} /> Quit Quiz
          </button>

          <div className="bg-white p-8 rounded-3xl shadow-sm">
            <h1 className="text-3xl font-bold mb-2">{topic} Assessment</h1>
            <p className="text-gray-500 mb-8">Generated by OpenAI • {questions.length} Questions</p>

            {loading && !submitted && (
               <div className="text-center py-20">Generating your unique test...</div>
            )}

            {!loading && !submitted && (
              <div className="space-y-8">
                {questions.map((q, idx) => (
                  <div key={q.id} className="p-4 border border-gray-100 rounded-2xl">
                    <p className="font-bold text-lg mb-4">{idx + 1}. {q.question}</p>
                    <div className="space-y-2">
                      {q.options.map((opt: string) => (
                        <button
                          key={opt}
                          onClick={() => handleSelect(q.id, opt)}
                          className={`w-full text-left p-4 rounded-xl border-2 transition-all ${
                            userAnswers[q.id] === opt 
                              ? 'border-[#ff5734] bg-[#fff0ed] text-[#ff5734] font-bold' 
                              : 'border-gray-200 hover:border-gray-300'
                          }`}
                        >
                          {opt}
                        </button>
                      ))}
                    </div>
                  </div>
                ))}
                
                <button 
                  onClick={handleSubmit}
                  className="w-full py-4 bg-[#151313] text-white font-bold rounded-full hover:bg-gray-800 transition-colors"
                >
                  Submit Final Answers
                </button>
              </div>
            )}

            {submitted && result && (
               <div className="animate-in fade-in zoom-in duration-500">
                  <div className="text-center mb-8">
                     <div className="text-5xl font-bold text-[#151313] mb-2">{result.score}%</div>
                     <p className="text-gray-500">{result.feedback}</p>
                  </div>

                  <div className="space-y-4">
                     {result.answers.map((ans: any, i: number) => (
                        <div key={i} className={`p-4 rounded-xl border-l-4 ${ans.isCorrect ? 'border-green-500 bg-green-50' : 'border-red-500 bg-red-50'}`}>
                           <p className="font-bold mb-2">{ans.questionText}</p>
                           <div className="flex justify-between text-sm">
                              <span>Your Answer: {ans.selectedAnswer}</span>
                              {!ans.isCorrect && <span className="font-bold">Correct: {ans.correctAnswer}</span>}
                           </div>
                        </div>
                     ))}
                  </div>
                  
                  <button 
                    onClick={() => router.back()}
                    className="mt-8 w-full py-4 bg-[#ff5734] text-white font-bold rounded-full"
                  >
                    Return to Course
                  </button>
               </div>
            )}

          </div>
        </main>
      </div>
    </div>
  );
}